server:
  port: 8083
spring:
  application:
    name: bot-application
  jpa:
    show-sql: true
  datasource:
    platform: postgres
    username: ${DB_USER:user}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/crud-sample?createIfNotExists=false}
    password: ${DB_PASSWORD:user123}
    driverClassName: org.postgresql.Driver
